name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 9014680042
          password: sandeep@231

      - name: Determine App to Build
        id: app_to_build
        run: |
          if [[ -n $(git log --name-only --pretty=oneline --since=1.commit -- FirstApp/ | grep -E '^FirstApp/|^FirstApp$') ]]; then
            echo "::set-output name=app::FirstApp"
          elif [[ -n $(git log --name-only --pretty=oneline --since=1.commit -- SecondApp/ | grep -E '^SecondApp/|^SecondApp$') ]]; then
            echo "::set-output name=app::SecondApp"
          elif [[ -n $(git log --name-only --pretty=oneline --since=1.commit -- Modules/ | grep -E '^Modules/|^Modules$') ]]; then
            echo "::set-output name=app::Modules"
          else
            echo "::set-output name=app::Nonevalue"
          fi

      - name: Build and Push Docker Image
        env:
          APP_NAME: ${{ steps.app_to_build.outputs.app }}
        run: |
          if [[ $APP_NAME == "FirstApp" ]]; then
            docker build -t 9014680042/firstapp:poc ./FirstApp
            docker push 9014680042/firstapp:poc
          elif [[ $APP_NAME == "SecondApp" ]]; then
            docker build -t 9014680042/secondapp:poc ./SecondApp
            docker push 9014680042/secondapp:poc
          elif [[ $APP_NAME == "Modules" ]]; then
            docker build -t 9014680042/firstapp:poc ./Modules/FirstApp
            docker build -t 9014680042/secondapp:poc ./Modules/SecondApp
            docker push 9014680042/firstapp:poc
            docker push 9014680042/secondapp:poc
          fi
